// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizSystems.Models;

namespace QuizSystems.Migrations
{
    [DbContext(typeof(QuizContext))]
    [Migration("20220421113024_mig_3")]
    partial class mig_3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("QuizSystems.Models.OnlineExam", b =>
                {
                    b.Property<int>("QuizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Correctans")
                        .HasColumnType("TEXT");

                    b.Property<string>("Options1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Options2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Options3")
                        .HasColumnType("TEXT");

                    b.Property<string>("Options4")
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .HasColumnType("TEXT");

                    b.Property<int>("WebDataId")
                        .HasColumnType("INTEGER");

                    b.HasKey("QuizId");

                    b.ToTable("OnlineExams");
                });

            modelBuilder.Entity("QuizSystems.Models.WebData", b =>
                {
                    b.Property<int>("WebDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OnlineExamQuizId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuizId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WebDataContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebDataHead")
                        .HasColumnType("TEXT");

                    b.HasKey("WebDataId");

                    b.HasIndex("OnlineExamQuizId");

                    b.ToTable("WebData");
                });

            modelBuilder.Entity("QuizSystems.Models.WebData", b =>
                {
                    b.HasOne("QuizSystems.Models.OnlineExam", "OnlineExam")
                        .WithMany("WebDatas")
                        .HasForeignKey("OnlineExamQuizId");

                    b.Navigation("OnlineExam");
                });

            modelBuilder.Entity("QuizSystems.Models.OnlineExam", b =>
                {
                    b.Navigation("WebDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
