// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizSystems.Models;

namespace QuizSystems.Migrations
{
    [DbContext(typeof(QuizContext))]
    [Migration("20220421095022_mig_2")]
    partial class mig_2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("QuizSystems.Models.OnlineExam", b =>
                {
                    b.Property<int>("QuizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Correctans")
                        .HasColumnType("TEXT");

                    b.Property<string>("Options1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Options2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Options3")
                        .HasColumnType("TEXT");

                    b.Property<string>("Options4")
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .HasColumnType("TEXT");

                    b.HasKey("QuizId");

                    b.ToTable("OnlineExams");
                });
#pragma warning restore 612, 618
        }
    }
}
